#!/bin/bash

#   Configuration variables used in this script,
#+ and in the configuration files' templates.
#
MW_Ver=${5-'1.35.5'}

# Wiki configuration:
Apex=wikido.xyz
MW_Instance_Dir=mw
URL_Prefix=""		#with leading slash. Used not in this script, but in templates
Repo_Alias=repo	#Also used not in this script, but in templates

# Directories:
MW_Source=/srv/app/mediawiki/$MW_Ver/core
Templates_Dir=/srv/src/wikitools/templates
Web_Root=/srv/www
Repo_Root=/srv/repositorea
Cache_Root=/var/cache
Temp_Root=/var/tmp
Secrets_Dir=/srv/websecrets

# Templates:
DB_Template=$Templates_Dir/wikido.xyz.mw-$MW_Ver.sql
LocalSettings_Template=$Templates_Dir/LocalSettings.template
Apache_Template=$Templates_Dir/apache.$Apex.conf.template
Robots_Template=$Templates_Dir/robots.txt.template
Secrets_Template=$Templates_Dir/secrets.template
Logo_Template=$Templates_Dir/wikido.xyz-logo.svg.template

###=========
if [[ -z $1 || -z $2 || -z $3 || -z $4 ]]; then
	cat <<- USAGE >&2
		WikiFamily configuration generator, and database creator.
		usage:
		  $(basename $0) <handle> <title> <username> <password> <mw_ver>
		where:
		    <handle>: A string to be used as the the hostname for the wiki website, as well as the base of both the database name and database username.
		    <title>: The natural language title of the wikisite.
		    <username>: Username of the first user to be created; and granted both "sysop" and "bureaucrat" status.
		    <password>: Password for aforementioned user.
		    <mw_version>: an optoinal MW version number to construct paths. Currently defaults to $MW_Ver
		More configuration variables exist in the code to customise the process.
		This scritp needs to be run as root. All arguments are required.
USAGE
	exit 85
fi
if ! [ $(id -u) = 0 ]; then
   echo "The script needs to be run as root." >&2
   exit 1
else
    real_user=$SUDO_USER
fi

Wiki_Handle=$1
Wiki_Title=$2
Wiki_Username=$3
Wiki_Password=$4

echo -e "Creating instance for:\nHandle: $Wiki_Handle\nTitle: $Wiki_Title\nMW version: $MW_Ver" >&2


# Derivative constants:
WIKI_FQDN=$Wiki_Handle.$Apex
WIKI_ROOT=$Web_Root/$Apex/$Wiki_Handle
REPOSITORY_DIR=$Repo_Root/$Apex/$Wiki_Handle
CACHE_DIR=$Cache_Root/$Apex/$Wiki_Handle
TEMP_DIR=$Temp_Root/$Apex/$Wiki_Handle
DB_NAME=${Wiki_Handle}_wiki
DB_USER=wiki_${Wiki_Handle}


conf_from_template() {
# Magically generates configuration files based on templates.
  TEMPLATE=$1
  shift
  eval "`printf 'local %s\n' $@`
  cat <<EOF
`sudo -u www-data cat $TEMPLATE`
EOF"
}


# Create directories and most needed symbolic links, acting as the Apache user
sudo -u www-data mkdir --parents $WIKI_ROOT
sudo -u www-data ln --symbolic $MW_Source $WIKI_ROOT/$MW_Instance_Dir
sudo -u www-data cp --recursive $MW_Source/images $REPOSITORY_DIR
sudo -u www-data cp --recursive $MW_Source/cache $CACHE_DIR
sudo -u www-data mkdir --parents $TEMP_DIR
mkdir --parents $Secrets_Dir && chgrp www-data $Secrets_Dir

# Generate LocalSettings.php for the wiki instance
# This instance-specific file is invoked from a dispatcher at the wikifamily-level
conf_from_template "$LocalSettings_Template" > "$WIKI_ROOT/LocalSettings.php"

#Generate Apache configuration
conf_from_template "$Apache_Template" > "/etc/apache2/sites-available/$WIKI_FQDN.conf"

sudo -u www-data cp "$Robots_Template" "$WIKI_ROOT/robots.txt"

#Generate websecrets files ##This is entropy-expensive, so better not run it unless it's feasible
DB_PASSWORD=$(apg -a1 -n1 -m16 -MNCL -d)

conf_from_template "$Secrets_Template" > "$Secrets_Dir/$Wiki_Handle.$Apex"
chmod u=r,g=r,o=- "$Secrets_Dir/$Wiki_Handle.$Apex"

#Create database
echo "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD'; CREATE DATABASE $DB_NAME; GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';" | mysql --user=root --password && echo -e "Successfuly created database $DB_NAME; user $DB_USER, and granted permissions.\nDatabase user's password is $DB_PASSWORD." >&2

mysql --user=$DB_USER --password=$DB_PASSWORD $DB_NAME < $DB_Template && echo "Successfuly created Mediawiki tables in $DB_NAME." >&2


#create 1st wiki user
sudo -u www-data php "$MW_Source/maintenance/createAndPromote.php" --bureaucrat --sysop --wiki "$DB_NAME" "$Wiki_Username" $Wiki_Password

sudo -u www-data php "$MW_Source/maintenance/install.php

#create logo
HANDLE_HASH=$(echo -n $Wiki_Handle | md5sum)

COLOUR1=${HANDLE_HASH:0:6}
COLOUR2=$(for o in {0..4..2}; do printf '%02X' $(( (0x${HANDLE_HASH:o:2} + 0x80) % 0xFF )); done)

if [[ 0x$COLOUR1 -lt 0x$COLOUR2 ]]; then
	FILL1=#$COLOUR2
	FILL2=#$COLOUR1
else
	FILL1=#$COLOUR1
	FILL2=#$COLOUR2
fi
conf_from_template "$Logo_Template" > $WIKI_ROOT/logo.svg
sudo -u www-data php $MW_Source/maintenance/importImages.php --wiki $DB_NAME --extensions=svg --skip-dupes --comment='شعار ويكي $WIKI_FQDN بألوان مستنبطة من عنوانها' --license='برخصة_المشاع_الإبداعي_النسبة_4.0' $WIKI_ROOT


a2ensite $WIKI_FQDN.conf

#restart apache if configuration is OK
apache2ctl configtest && apache2ctl restart
